services: 
  back-end:
    build: 
      context: node
    container_name: back-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - /home/regraced/nodeTest/node:/usr/src/app  # Update for back-end
      - backend-node-modules:/usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start

  front-end:
    build: 
      context: react
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - /home/regraced/nodeTest/react:/usr/src/app  # Update for front-end
      - frontend-node-modules:/usr/src/app/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - back-end
       - front-end

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    tty: true
    ports: 
      - 6379:6379
      - 8001:8001
    networks:
      - node-network
    volumes:
      - redis-data:/data
  
networks: 
  node-network:
    driver: bridge

volumes: 
  redis-data:
    driver: local
  backend-node-modules:
    driver: local
  frontend-node-modules:
    driver: local
